### ISSUE TITLE
New function for calculating contributions by time

### ISSUE THREAD

**Issue by mmc46** [jefferis/elmr#42]
This is possible in pymaid. And using time contributions is the suggested way in FAFB guidelines, so it would be good to have a function to allow this.

**Comment by jefferis** [comment]
Ok can you ask Philipp to point to code implementing pymaid methodology?

**Comment by mmc46** [comment]
https://github.com/schlegelp/pyMaid/blob/58f394dff33d9f267279483bf6e327ed339d868a/pymaid/user_stats.py#L536

**Comment by jefferis** [comment]
This is happening in catmaid so we can close here.
