### ISSUE TITLE
Can xform_brain return voxel values instead of coordinates when mapping from light microscopy to FAFB?

### ISSUE THREAD

**Issue by r-shruthi11** [jefferis/elmr#43]
Hello, I'm trying to transform a skeleton registered to JFRC2 (for eg. this neuron in VFB - http://www.virtualflybrain.org/data/VFB/i/0000/6602/volume.swc) to find the corresponding coordinates in FAFBv14 space using xform_brain. I believe the values returned by xform_brain are in the units of nanometers; I wonder if there is a simple transform that will map these values to FAFB voxels? Thank you!

**Comment by jefferis** [comment]
You can take the returned object and divide by the voxel size.

```
myneurons.raw=myneurons.fafb14/voxdims(FAFB14)
```

**Comment by jefferis** [comment]
PS this group: 
http://groups.google.com/forum/#!forum/nat-user 
is a good placefor this kind of question

**Comment by r-shruthi11** [comment]
Thanks! I'll post to this group in the future

**Comment by jefferis** [comment]
Great. Of course do continue to use GitHub issues for bug reports.
